apiVersion: v1
kind: Namespace
metadata:
  name: ldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
spec:
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.2.3
        ports:
        - name: ldap389
          containerPort: 389
        - name: ldap636
          containerPort: 636
        env:
        - name: LDAP_LOG_LEVEL
          value: "256"
        - name: LDAP_DOMAIN
          value: "mycompany.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "adminpassword"
        - name: LDAP_CONFIG_PASSWORD
          value: "config"
        - name: LDAP_READONLY_USER
          value: "false"
        - name: LDAP_READONLY_USER_USERNAME
          value: "readonly"
        - name: LDAP_READONLY_USER_PASSWORD
          value: "readonly"
        - name: LDAP_RFC2307BIS_SCHEMA
          value: "false"
        - name: LDAP_BACKEND
          value: "mdb"
        - name: LDAP_REPLICATION
          value: "false"
        - name: KEEP_EXISTING_CONFIG
          value: "false"
        - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: osixia/phpldapadmin:0.9.0
        ports:
        - name: http
          containerPort: 80 
        env:
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: 10.233.75.39
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-authorization
  namespace: ldap
spec:
  selector:
    matchLabels:
      app: webhook_authorization
  template:
    metadata:
      labels:
        app: webhook_authorization
    spec:
      containers:
      - name: webhook
        image: vadim46/ldap-webhook:latest
        ports:
        - name: https
          containerPort: 443
        env:
        - name: IP
          value: 10.233.75.39
