apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-phpldapadmin
  annotations:
    {{if .Values.tls.enabled }}cert-manager.io/cluster-issuer: {{ .Values.tls.issuer}}{{end}}
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: phpldapadmin
      port:
        number: 80
  rules:
  - host: webhook.{{ .Release.Name }}
    http:
      paths:
      - pathType: Prefix
        path: /phpldapadmin
        backend:
          service:
            name: phpldapadmin
            port:
              number: 80
  {{if .Values.tls.enabled}}
  tls:
  - hosts:
    - webhook.{{ .Release.Name }}
    secretName: {{ .Values.tls.secret }} 
  {{end}}

